# Generated by Django 4.0.5 on 2022-10-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_venuesavailable_user_actual_form_user_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="school",
            field=models.CharField(max_length=255),
        ),
    ]
