# Generated by Django 4.0.5 on 2022-10-03 00:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VenuesAvailable",
            new_name="Venue",
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+7 916 386-30-90",
                max_length=128,
                region=None,
                unique=True,
                verbose_name="Phone",
            ),
            preserve_default=False,
        ),
    ]
