# Generated by Django 4.0.5 on 2022-10-03 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_venuesavailable_venue_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '(\\d{4} \\d{6})|(..-.. \\d{6})'
                    )
                ],
                verbose_name='Passport',
            ),
        ),
    ]
