# Generated by Django 4.0.5 on 2022-10-03 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_passport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passport",
            field=models.CharField(
                help_text="Passport in format xxxx xxxxxx or birth proof in format XX-XX xxxxxx",
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "(\\d{4} \\d{6})|(..-.. \\d{6})"
                    )
                ],
                verbose_name="Passport",
            ),
        ),
    ]
