# Generated by Django 4.0.5 on 2022-10-19 14:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_online_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('p', 'Participant'), ('a', 'Admin'), ('j', 'Judge')],
                default='p',
                editable=False,
                max_length=1,
                verbose_name='Role',
            ),
        ),
        migrations.CreateModel(
            name='OfflineResult',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'score',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        size=5,
                        verbose_name='Scores',
                    ),
                ),
                (
                    'comment',
                    models.TextField(blank=True, default='', verbose_name='Comment'),
                ),
                (
                    'paper_original',
                    models.FileField(
                        upload_to='originals', verbose_name='Original work'
                    ),
                ),
                (
                    'paper_annotated',
                    models.FileField(
                        upload_to='annotated', verbose_name='Annotated work'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Participant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Result (offline)',
                'verbose_name_plural': 'Results (offline)',
            },
        ),
    ]
