# Generated by Django 4.0.5 on 2022-10-19 14:42
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_role_offlineresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offlineresult",
            old_name="score",
            new_name="scores",
        ),
    ]
