# Generated by Django 4.0.5 on 2022-10-20 19:46
from __future__ import annotations

from django.db import migrations

import concurrency.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_offlineresult_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="offlineresult",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="record revision number"
            ),
        ),
    ]
