# Generated by Django 4.0.5 on 2022-10-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_offlineresult_scores"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "file",
                    models.FileField(upload_to="problems", verbose_name="Statement"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Annotation content"
                    ),
                ),
                ("opens", models.DateTimeField(verbose_name="Opens at")),
                ("closes", models.DateTimeField(verbose_name="Closes at")),
                ("duration", models.DurationField(verbose_name="Duration")),
            ],
            options={
                "verbose_name": "Problem",
                "verbose_name_plural": "Problems",
            },
        ),
        migrations.CreateModel(
            name="OnlineSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Solution file in pdf format",
                        null=True,
                        upload_to="online_submissions",
                        verbose_name="Solution file",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Comment"),
                ),
                ("started", models.DateTimeField(verbose_name="Started at")),
                (
                    "problem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.onlineproblem",
                        verbose_name="Problem",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
            },
        ),
    ]
