# Generated by Django 4.0.5 on 2022-10-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_onlineproblem_onlinesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineproblem",
            name="visible",
            field=models.BooleanField(default=False, verbose_name="Visible"),
        ),
    ]
