# Generated by Django 4.0.5 on 2022-10-22 22:54
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_onlineproblem_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlinesubmission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participant",
            ),
        ),
    ]
