# Generated by Django 4.0.5 on 2022-11-17 14:37
from __future__ import annotations

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0034_alter_offlineresult_final_scores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinesubmission",
            name="final_scores",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, default="", max_length=4),
                blank=True,
                default=list,
                size=4,
                verbose_name="Final scores after appellation",
            ),
        ),
        migrations.AddField(
            model_name="onlinesubmission",
            name="scores",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, default="", max_length=4),
                blank=True,
                default=list,
                size=4,
                verbose_name="Scores",
            ),
        ),
    ]
