# Generated by Django 4.0.5 on 2022-11-17 14:54
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_onlinesubmission_final_scores_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onlinesubmission",
            old_name="file",
            new_name="paper_original",
        ),
    ]
