# Generated by Django 4.0.5 on 2022-12-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_alter_appellation_options_onlineappellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineproblem",
            name="solution",
            field=models.FileField(
                default=None, upload_to="solutions", verbose_name="Solutions", null=True
            ),
            preserve_default=False,
        ),
    ]
