# Generated by Django 4.0.5 on 2023-09-16 12:55

import pathlib

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_configurationsingleton_venue_registration_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='confirmation_letter',
            field=models.FileField(
                help_text='A photo or scan of a confirmation signed by your institution authority',
                null=True,
                upload_to=pathlib.PurePosixPath(
                    '/var/www/rechol_user_section/media/venue_confirmation_letters'
                ),
                verbose_name='Confirmation letter',
            ),
        ),
        migrations.AddField(
            model_name='venue',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                default='', max_length=128, region=None, verbose_name='Phone'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_venue',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
            preserve_default=False,
        ),
    ]
