# Generated by Django 4.0.5 on 2023-09-16 15:29
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0044_configurationsingleton_forbid_venue_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="venue_selected",
            field=models.ForeignKey(
                blank=True,
                help_text="Select only if you plan to participate in offline stage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.venue",
                verbose_name="Venue",
            ),
        ),
    ]
