# Generated by Django 4.0.10 on 2023-10-31 23:00
from __future__ import annotations

from django.db import migrations

import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0050_onlineproblem_file_en_onlineproblem_solution_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="country",
            field=django_countries.fields.CountryField(
                default="RU", max_length=2, verbose_name="Country"
            ),
        ),
    ]
