# Generated by Django 4.0.10 on 2023-10-31 23:06
from __future__ import annotations

from django.db import migrations

import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0051_venue_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="country",
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                default="RU", max_length=2, verbose_name="Country"
            ),
        ),
    ]
