# Generated by Django 4.0.10 on 2023-10-31 23:06

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0051_venue_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="country",
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                default="RU", max_length=2, verbose_name="Country"
            ),
        ),
    ]
