# Generated by Django 4.0.10 on 2023-11-22 02:55
from __future__ import annotations

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0055_remove_onlineproblem_comment_offlineproblem_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineproblem",
            name="closes_en",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 22, 2, 55, 28, 594417, tzinfo=utc),
                verbose_name="Closes at (en)",
            ),
            preserve_default=False,
        ),
    ]
