# Generated by Django 4.0.10 on 2024-01-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_organizercertificate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizercertificate',
            name='first_name_gen',
            field=models.CharField(max_length=255, verbose_name='first name (dativ)'),
        ),
        migrations.AlterField(
            model_name='organizercertificate',
            name='last_name_gen',
            field=models.CharField(max_length=255, verbose_name='last name (dativ)'),
        ),
        migrations.AlterField(
            model_name='organizercertificate',
            name='middle_name_gen',
            field=models.CharField(blank=True, max_length=255, verbose_name='middle name (dativ)'),
        ),
    ]
