# Generated by Django 4.2.15 on 2024-09-14 19:41
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0059_alter_organizercertificate_first_name_gen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
    ]
