# Root files
.gitignore
.pre-commit-config.yaml
bitbucket-pipelines.yml
docker-compose.yaml
docker-compose.*.yaml
Dockerfile
Dockerfile.*
pylintrc
*.md

# Folders
docs
logs
src
templates
tests

# .gitignore copy
.local
.env
venv
logs
_build
_static
_templates
node_modules/
dist/
__pycache__/
.pytest_cache
*.py[cod]
*$py.class
*.log
dist/
.idea/
TEST*.xml
.DS_Store
Thumbs.db
*.app
*.sublime-*
db_data
